-- Posts table seeds here (Example)

INSERT INTO posts
  (owner_id, title, post_description, url_address, image_url, category_id)
VALUES
  (1, '11 Things You Must Do With a Brand New Laptop', 'Here are the most important things to do when you get a new laptop to help your computer run at its best.', 'https://www.makeuseof.com/tag/things-must-do-brand-new-laptop/', 'https://i.pinimg.com/564x/27/d2/f8/27d2f87ca6a1da4025397bce8147e414.jpg', 1),
  (2, 'Leisure Activities', 'Leisure activities have a great benefit for mental health symptoms. Here is benefits of leisure activities for anxiety, depression, schizophrenia, and more.', 'https://selfcareoverload.com/2019/05/15/leisure-activities/', 'https://i.pinimg.com/564x/66/3e/f4/663ef4117bf05f5e96799b7a00147349.jpg', 2),
  (3, 'Vertical Jump', 'How To Improve Vertical Jump For Basketball Players - Air Defying Secrets', 'http://mrverticaljump.hubpages.com/hub/How-To-Improve-Vertical-Jump-For-Basketball-Players-Air-Defying-Secrets', 'https://i.pinimg.com/564x/5b/f6/67/5bf667c65a2e0662bc61ed0c2471a31f.jpg', 3),
  (4, 'Change Habits', 'Want to get healthier? You do not have to revamp your whole life at once. Here are 10 two-minute habits science says will change your life for the better.', 'http://www.livestrong.com/slideshow/1012823-10-2minute-habits-change-life/?crlt.pid=camp.U3szKreoUVz0', 'https://i.pinimg.com/564x/e2/34/38/e23438292df112b4528c7e58852a35d0.jpg', 4),
  (5, 'Easy Acoustic Guitar Songs for Beginners', 'Want to play some guitar quick? Check out these songs you can start playing right away at the campfire or beach or home.', 'https://soundchecklab.com/easy-acoustic-guitar-songs-for-beginners/', 'https://i.pinimg.com/564x/c8/ec/41/c8ec41b305efe3b832cafdcf3dd635ff.jpg', 5),
  (6, 'How To Write a Good Video Game Story', 'Whether you’ve been playing video games since you were a kid or have recently noticed them as an exciting new medium to tell your story in, you may be wondering how to write a good video game story. After all, video games seem deeply complex and overwhelming—not to mention all the development work', 'https://www.emwelsh.com/blog/write-good-video-game-story', 'https://i.pinimg.com/564x/19/05/df/1905df70ee0cbbf62eb2a42b6db35262.jpg', 6),
  (7, 'Travel Essentials', 'Travel Essentials: 22 Things Every Traveler Should Pack – The Travel Bite', 'https://thetravelbite.com/travel-tips/carry-on-travel-essentials/?utm_medium=social&utm_source=pinterest&utm_campaign=tailwind_smartloop&utm_content=smartloop&utm_term=3976472', 'https://i.pinimg.com/564x/50/6a/4b/506a4bdfdbabaf8a43286ab7d89f78bc.jpg', 7),
  (8, 'Politics In The Classroom', 'Two authors argue that teachers should embrace controversial issues to help students learn the political process. But, they say, context is key.', 'https://www.npr.org/sections/ed/2015/08/06/415498760/the-role-of-politics-in-the-classroom', 'https://i.pinimg.com/564x/0e/a4/99/0ea499ad5fed4f6d7996b416db6ec515.jpg', 8),
  (9, 'Python Projects for Beginners', 'So you are learning Python programming and you just want to start building your first Python coding projects? Use these ideas and tutorials for beginners to code practical projects for your developer portfolio website. Whether for data science, web development, artificial intelligence, machine learning, or software development, Python is the perfect tool for you!', 'https://mikkegoes.com/python-projects-for-beginners/', 'https://i.pinimg.com/564x/c5/6d/c7/c56dc78a524618bee333ee1f922f5551.jpg', 9),
  (10, 'How To Network Like a Pro', 'Are you an introvert who hates networking? Learn tips on how to rock your next networking event easily and comfortably to make the most of the event and exponentially grow your creative business and be that.', 'https://www.clairedobson.com/blog/how-to-network-like-a-pro-introvert?utm_medium=social&utm_source=pinterest&utm_campaign=tailwind_tribes&utm_content=tribes&utm_term=551195094_20244986_155686', 'https://i.pinimg.com/564x/13/7d/90/137d90fb76281b1afdf1b088c22d0c86.jpg', 10),
  (11, '50 At Home Date Night Ideas', 'Stay at home date ideas for when staying in sounds better than going out. 50 fun and romantic ideas for couples.', 'https://collegelifemadeeasy.com/50-budget-friendly-creative-stay-at-home-date-ideas/', 'https://collegelifemadeeasy.com/wp-content/uploads/2018/01/stay-at-home-date-ideas-infographic.jpg', 11),
  (12, 'How To Remember What You Read', 'It is all well and good to read a lot of books. You flip those pages every night before bed, at every bus stop, and on every lunch break. You watch your bookshelf pile up with tomes you have torn through in record time. But what good is all that effort if you do not remember what you read?', 'https://keepingupwiththepenguins.com/how-to-remember-what-you-read/', 'https://i.pinimg.com/564x/18/e1/df/18e1df7f8440f25434674a0cb6c40a59.jpg', 12),
  (13, 'Astronaut Alphabet', 'Check out the view from outer space! The planets are covered with letters! Place a planet in the astronaut view, then write the letter on the white space using a dry erase marker. You can even tape this activity on the underside of a table to write like the astronauts!', 'https://www.teacherspayteachers.com/Product/Astronaut-ABC-Writing-Letter-Match-Activity-4276106', 'https://i.pinimg.com/564x/c0/01/0a/c0010a50948b2ce1a257f322115b5cb7.jpg', 13),
  (14, '7 Lessons Learned From Cryptocurrency Investing', 'Do you want to start investing in the cryptocurrency market? Learn from my mistakes and check out these 7 lessons learned from investing in cryptocurrency. Cryptocurrency trading, investing, the blockchain, Bitcoin, and mining need some further explanation! Check out my lessons and do not make the same mistakes I did', 'https://radicalfire.com/lessons-learned-cryptocurrencies/', 'https://i.pinimg.com/564x/35/1c/6f/351c6f644b8560b2694953a73e2e573e.jpg', 14),
  (15, 'Best Online Virtual Japanese Cooking Classes', 'Join our expert chefs and cooks from Tokyo and make the most of your lockdown with a private online Japanese cooking class. Learn to cook Japanese specialities to get the taste of Japan in your own kitchen. A great cultural experience and international connection!', 'https://asocialnomad.com/japan/japanese-cooking-class-in-japan/?utm_medium=social&utm_source=pinterest&utm_campaign=tailwind_tribes&utm_content=tribes&utm_term=1066254324_50502706_493074', 'https://i.pinimg.com/564x/c4/4f/71/c44f718719cb0fbeff5c064ddf90540b.jpg', 15);






