INSERT INTO user_feedbacks
  (user_id, post_id, likes, comment, rating)
VALUES
  (14, 15, 'TRUE', 'If cartoon bluebirds were real, a bunch of them would be sitting on your shoulders singing right now.', 4),
  (12, 14, 'FALSE', 'Your ability to recall random factoids at just the right time is impressive.', 3),
  (14, 13, 'TRUE', 'If you were a box of crayons, you’d be the giant name-brand one with the built-in sharpener.', 5),
  (4, 12, 'TRUE', 'You’re always learning new things and trying to better yourself, which is awesome.', 4),
  (11, 11, 'TRUE', 'Who raised you? They deserve a medal for a job well done.', 3),
  (12, 10, 'FALSE', 'Your creative potential seems limitless.', 4),
  (13, 9, 'FALSE', 'You could survive a zombie apocalypse.', 3),
  (8, 8, 'FALSE', 'Actions speak louder than words, and yours tell an incredible story.', 3),
  (4, 7, 'TRUE', 'You’re a smart cookie.', 5),
  (3, 6, 'TRUE', 'You’re more helpful than you realize.', 1),
  (12, 5, 'TRUE', 'Your work has such personality.', 2),
  (1, 4, 'FALSE', 'Your good knowledge and kindness in playing with all the pieces were very useful.', 4),
  (9, 3, 'TRUE', 'Your perspective is refreshing, thank you.', 4),
  (2, 2, 'FALSE', 'You are becoming an expert at this.', 1),
  (6, 1, 'TRUE', 'Thanks for one marvelous posting! I enjoyed reading it; you are a great author.', 5),

  (14, 30, 'TRUE', 'If cartoon bluebirds were real, a bunch of them would be sitting on your shoulders singing right now.', 4),
  (12, 29, 'FALSE', 'Your ability to recall random factoids at just the right time is impressive.', 3),
  (14, 28, 'TRUE', 'If you were a box of crayons, you’d be the giant name-brand one with the built-in sharpener.', 5),
  (1, 27, 'TRUE', 'You’re always learning new things and trying to better yourself, which is awesome.', 4),
  (2, 26, 'TRUE', 'Who raised you? They deserve a medal for a job well done.', 3),
  (12, 25, 'FALSE', 'Your creative potential seems limitless.', 4),
  (13, 24, 'FALSE', 'You could survive a zombie apocalypse.', 3),
  (8, 23, 'FALSE', 'Actions speak louder than words, and yours tell an incredible story.', 3),
  (4, 22, 'TRUE', 'You’re a smart cookie.', 5),
  (3, 21, 'TRUE', 'You’re more helpful than you realize.', 1),
  (1, 20, 'TRUE', 'Your work has such personality.', 2),
  (1, 19, 'FALSE', 'Your good knowledge and kindness in playing with all the pieces were very useful.', 4),
  (9, 18, 'TRUE', 'Your perspective is refreshing, thank you.', 4),
  (2, 17, 'FALSE', 'You are becoming an expert at this.', 1),
  (6, 16, 'TRUE', 'Thanks for one marvelous posting! I enjoyed reading it; you are a great author.', 5),

  (14, 45, 'TRUE', 'If cartoon bluebirds were real, a bunch of them would be sitting on your shoulders singing right now.', 4),
  (12, 44, 'FALSE', 'Your ability to recall random factoids at just the right time is impressive.', 3),
  (14, 43, 'TRUE', 'If you were a box of crayons, you’d be the giant name-brand one with the built-in sharpener.', 5),
  (4, 42, 'TRUE', 'You’re always learning new things and trying to better yourself, which is awesome.', 4),
  (11, 41, 'TRUE', 'Who raised you? They deserve a medal for a job well done.', 3),
  (12, 40, 'FALSE', 'Your creative potential seems limitless.', 4),
  (13, 39, 'FALSE', 'You could survive a zombie apocalypse.', 3),
  (8, 38, 'FALSE', 'Actions speak louder than words, and yours tell an incredible story.', 3),
  (4, 37, 'TRUE', 'You’re a smart cookie.', 5),
  (3, 36, 'TRUE', 'You’re more helpful than you realize.', 1),
  (12, 35, 'TRUE', 'Your work has such personality.', 2),
  (1, 34, 'FALSE', 'Your good knowledge and kindness in playing with all the pieces were very useful.', 4),
  (9, 33, 'TRUE', 'Your perspective is refreshing, thank you.', 4),
  (2, 32, 'FALSE', 'You are becoming an expert at this.', 1),
  (6, 31, 'TRUE', 'Thanks for one marvelous posting! I enjoyed reading it; you are a great author.', 5);
