DROP TABLE IF EXISTS user_feedbacks CASCADE;

CREATE TABLE user_feedbacks (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  post_id INTEGER REFERENCES posts(id) ON DELETE CASCADE,
  likes BOOLEAN NOT NULL DEFAULT FALSE,
  comment text,
  rating SMALLINT NOT NULL DEFAULT 0
);
